apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: splunkenterprise
  name: splunkenterprise
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: splunkenterprise
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\kompose\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: splunkenterprise
    spec:
      containers:
        - env:
            - name: SPLUNK_ADD
              value: tcp 1514
            - name: SPLUNK_ENABLE_LISTEN
              value: "9997"
            - name: SPLUNK_PASSWORD
              value: Gwenbleidd@32
            - name: SPLUNK_START_ARGS
              value: --accept-license
          image: splunk/splunk  # splunk/splunk previos image gcr.io/pooper-scooper/splunk-it:latest
          name: splunkenterprise
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 9997
              protocol: TCP
            - containerPort: 8088
              protocol: TCP
            - containerPort: 1514
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/splunk/etc
              name: opt-splunk-etc
            - mountPath: /opt/splunk/var
              name: opt-splunk-var
      hostname: splunkenterprise
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: opt-splunk-etc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi  # Size of each replica's PVC
      storageClassName: "poopers"  # Adjust based on your environment
  - metadata:
      name: opt-splunk-var
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi  # Size of each replica's PVC
      storageClassName: "poopers"
