apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\kompose\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
    cloud.google.com/load-balancer-type: "EXTERNAL"
    service.beta.kubernetes.io/external-traffic-policy: "Local"  # Ensures traffic stays on the same node for affinity
    service.beta.kubernetes.io/enable-session-affinity: "true"
  labels:
    io.kompose.service: splunkenterprise
  name: splunkenterprise
spec:
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "9997"
      port: 9997
      targetPort: 9997
    - name: "8088"
      port: 8088
      targetPort: 8088
    - name: "1514"
      port: 1514
      targetPort: 1514
  selector:
    io.kompose.service: splunkenterprise
