apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: poopers
provisioner: kubernetes.io/gce-pd  # GCP-specific provisioner for Persistent Disks
parameters:
  type: pd-ssd  # Defines the disk type (SSD)
  replication-type: none
reclaimPolicy: Delete  # Keeps the PV even if the PVC is deleted
allowVolumeExpansion: true  # Allows increasing the size of the volume
